/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package course;

import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Dhanish Aswin
 */
public class feedbackform extends javax.swing.JFrame {

    /**
     * Creates new form feedbackform
     */
    public feedbackform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jRadioButton4 = new javax.swing.JRadioButton();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jRadioButton2 = new javax.swing.JRadioButton();
        rollno = new javax.swing.JPanel();
        execellent = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        vgood = new javax.swing.JRadioButton();
        good = new javax.swing.JRadioButton();
        department = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        fair = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        rollno1 = new javax.swing.JTextField();
        subject = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sd = new javax.swing.JRadioButton();
        ag = new javax.swing.JRadioButton();
        nut = new javax.swing.JRadioButton();
        d = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        vo = new javax.swing.JRadioButton();
        st = new javax.swing.JRadioButton();
        r = new javax.swing.JRadioButton();
        n = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        ns = new javax.swing.JRadioButton();
        sf = new javax.swing.JRadioButton();
        nu = new javax.swing.JRadioButton();
        vs = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        fee = new javax.swing.JTextField();

        jRadioButton4.setText("jRadioButton4");

        jRadioButton2.setText("jRadioButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rollno.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 51)), "feedback form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(0, 255, 51))); // NOI18N

        buttonGroup1.add(execellent);
        execellent.setText("excellent");
        execellent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                execellentActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ENTER ROLLNO");

        buttonGroup1.add(vgood);
        vgood.setText("v.good");

        buttonGroup1.add(good);
        good.setText("good");

        department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B.VOC.IT", "B.SC.CS", "B.C.A", " " }));
        department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentActionPerformed(evt);
            }
        });

        jLabel5.setText("A.communication skills(i.e faculty's ability to communicate the subject clearly and audibly)");

        buttonGroup1.add(fair);
        fair.setText("fair");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("ENTER SUBJECT:-");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("DEPARTMENT:-");

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("B.The school staff is caring and respects the students");

        buttonGroup7.add(sd);
        sd.setText("storingly disagree");

        buttonGroup7.add(ag);
        ag.setText("agree");

        buttonGroup7.add(nut);
        nut.setText("nutral");

        buttonGroup7.add(d);
        d.setText("disagree");

        jLabel4.setText("C.How often did you have the freedom to try innovative methods for better learning?");

        buttonGroup3.add(vo);
        vo.setText("very often");

        buttonGroup3.add(st);
        st.setText("sometimes");

        buttonGroup3.add(r);
        r.setText("rarely");

        buttonGroup3.add(n);
        n.setText("never");

        jLabel8.setText("E.encouraging the student it think independently creatively & criticaly");

        buttonGroup4.add(ns);
        ns.setText("not satisfied");

        buttonGroup4.add(sf);
        sf.setText("satisfied");

        buttonGroup4.add(nu);
        nu.setText("nutral");

        buttonGroup4.add(vs);
        vs.setText("very satisfied");

        jLabel9.setText("things to be improved");

        javax.swing.GroupLayout rollnoLayout = new javax.swing.GroupLayout(rollno);
        rollno.setLayout(rollnoLayout);
        rollnoLayout.setHorizontalGroup(
            rollnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rollnoLayout.createSequentialGroup()
                .addGroup(rollnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rollnoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(rollnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(rollnoLayout.createSequentialGroup()
                                .addGroup(rollnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(25, 25, 25)
                                .addGroup(rollnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(department, 0, 150, Short.MAX_VALUE)
                                    .addComponent(rollno1)
                                    .addComponent(subject)))
                            .addGroup(rollnoLayout.createSequentialGroup()
                                .addComponent(execellent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(vgood)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(good)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fair))))
                    .addGroup(rollnoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(rollnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(rollnoLayout.createSequentialGroup()
                                .addGroup(rollnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addGroup(rollnoLayout.createSequentialGroup()
                                        .addComponent(sd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ag)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(rollnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(rollnoLayout.createSequentialGroup()
                                        .addComponent(d)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nut))
                                    .addComponent(jButton2)))))
                    .addGroup(rollnoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(rollnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rollnoLayout.createSequentialGroup()
                                .addComponent(vo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(st)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(r)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(n))
                            .addGroup(rollnoLayout.createSequentialGroup()
                                .addComponent(ns)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(vs))
                            .addComponent(jLabel9)
                            .addComponent(fee, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(rollnoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(rollnoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addGap(45, 45, 45))
        );
        rollnoLayout.setVerticalGroup(
            rollnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rollnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rollnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rollnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rollno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rollnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rollnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(execellent)
                    .addComponent(vgood)
                    .addComponent(good)
                    .addComponent(fair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rollnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sd)
                    .addComponent(ag)
                    .addComponent(d)
                    .addComponent(nut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rollnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vo)
                    .addComponent(st)
                    .addComponent(r)
                    .addComponent(n))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rollnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ns)
                    .addComponent(sf)
                    .addComponent(nu)
                    .addComponent(vs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(rollnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(rollno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rollno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void execellentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_execellentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_execellentActionPerformed

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            
            // TODO add your handling code here:

            Class.forName("com.mysql.jdbc.Driver");
            try {
                Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost/course feedback","root","");
                String sql ="insert into feedback(department,rollno,subject,communication,respect,innovative,holidays,improments) values(?,?,?,?,?,?,?,?)";
                PreparedStatement pstmt = con1.prepareStatement(sql);
                
                String dep;
                dep =department.getSelectedItem().toString();
                pstmt.setString(1, dep);
              
                
                pstmt.setString(2,rollno1.getText());
                pstmt.setString(3,subject.getText());
                
                
                String comskill = null ;
                if(execellent.isSelected()){
                    comskill = execellent.getText();
               }
                if(vgood.isSelected()){
                    comskill = vgood.getText();
                }
                if(good.isSelected()){
                    comskill = good.getText();
                }
                if(fair.isSelected())
                {
                    comskill=fair.getText();
                }
                pstmt.setString(4, comskill);
                
                
                String res = null ;
                if(sd.isSelected()){
                    res = sd.getText();
               }
                if(ag.isSelected()){
                    res = ag.getText();
                }
                if(d.isSelected()){
                    res = d.getText();
                }
                if(nut.isSelected())
                {
                    res=nut.getText();
                }
                pstmt.setString(5, res);
               

                String inn = null ;
                if(vo.isSelected()){
                    inn = vo.getText();
               }
                if(st.isSelected()){
                    inn = st.getText();
                }
                if(r.isSelected()){
                    inn = r.getText();
                }
                if(n.isSelected())
                {
                    inn=n.getText();
                }
                pstmt.setString(6, res);
                
                String hol = null ;
                if(ns.isSelected()){
                    hol =ns.getText();
               }
                if(sf.isSelected()){
                    hol = sf.getText();
                }
                if(nu.isSelected()){
                    hol = nu.getText();
                }
                if(vs.isSelected())
                {
                    hol=vs.getText();
                }
                
                pstmt.setString(7, hol);
                
                 pstmt.setString(8, fee.getText());
                pstmt.executeUpdate();
                
                 JOptionPane.showMessageDialog(null, "feedback addded");
              
                
                
                
            } catch (SQLException ex) {
                Logger.getLogger(feedbackform.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(feedbackform.class.getName()).log(Level.SEVERE, null, ex);
        }
         System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        first op= new first();
        op.setVisible(true);
         
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(feedbackform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(feedbackform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(feedbackform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(feedbackform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new feedbackform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ag;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JRadioButton d;
    private javax.swing.JComboBox<String> department;
    private javax.swing.JRadioButton execellent;
    private javax.swing.JRadioButton fair;
    private javax.swing.JTextField fee;
    private javax.swing.JRadioButton good;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton n;
    private javax.swing.JRadioButton ns;
    private javax.swing.JRadioButton nu;
    private javax.swing.JRadioButton nut;
    private javax.swing.JRadioButton r;
    private javax.swing.JPanel rollno;
    private javax.swing.JTextField rollno1;
    private javax.swing.JRadioButton sd;
    private javax.swing.JRadioButton sf;
    private javax.swing.JRadioButton st;
    private javax.swing.JTextField subject;
    private javax.swing.JRadioButton vgood;
    private javax.swing.JRadioButton vo;
    private javax.swing.JRadioButton vs;
    // End of variables declaration//GEN-END:variables
}
